#!/usr/bin/env python3
"""Convert Micro-AST to TFLite INT8 and generate C headers for firmware."""
from __future__ import annotations

import json
from pathlib import Path

import librosa
import numpy as np
import tensorflow as tf

from train_ast import (
    AddPositionalEmbedding, StaticMultiHeadAttention,
    SAMPLE_RATE, N_FFT, HOP_LENGTH, N_MELS, FMIN, FMAX,
    DURATION, N_SAMPLES, N_FRAMES, CLASSES,
)

TRAIN_DIR   = Path("data/train")
MODEL_DIR   = Path("models")
INCLUDE_DIR = Path("firmware/include")


def load_mel(path: Path, mean: float, std: float):
    try:
        y, _ = librosa.load(str(path), sr=SAMPLE_RATE, mono=True,
                            duration=DURATION)
        if len(y) < N_SAMPLES:
            y = np.pad(y, (0, N_SAMPLES - len(y)))
        y = y[:N_SAMPLES]
        mel = librosa.feature.melspectrogram(
            y=y, sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH,
            n_mels=N_MELS, fmin=FMIN, fmax=FMAX, center=False,
        )
        lm = librosa.power_to_db(mel, ref=np.max).astype(np.float32).T
        if lm.shape[0] > N_FRAMES:
            lm = lm[:N_FRAMES]
        elif lm.shape[0] < N_FRAMES:
            lm = np.pad(lm, ((0, N_FRAMES - lm.shape[0]), (0, 0)))
        return ((lm - mean) / std)[np.newaxis, ..., np.newaxis].astype(np.float32)
    except Exception:
        return None


def representative_dataset(mean: float, std: float):
    def gen():
        count = 0
        for cls_dir in sorted(TRAIN_DIR.iterdir()):
            if not cls_dir.is_dir():
                continue
            for wav in list(cls_dir.rglob("*.wav"))[:40]:
                mel = load_mel(wav, mean, std)
                if mel is not None:
                    yield [mel]
                    count += 1
                    if count >= 200:
                        return
    return gen


def bytes_to_c_array(data: bytes, var_name: str = "model_data") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk))
    return (
        "// Auto-generated by convert_ast.py — do not edit\n"
        "#pragma once\n\n"
        f"alignas(8) const unsigned char {var_name}[] = {{\n"
        + ",\n".join(lines)
        + "\n};\n"
        f"const unsigned int {var_name}_len = {len(data)};\n"
    )


def mel_filterbank_header(mean: float, std: float) -> str:
    fb = librosa.filters.mel(
        sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=N_MELS, fmin=FMIN, fmax=FMAX,
    ).astype(np.float32)
    n_mels, n_bins = fb.shape
    rows = ["  {" + ", ".join(f"{v:.8f}f" for v in row) + "}" for row in fb]
    return (
        "// Auto-generated by convert_ast.py — do not edit\n"
        "#pragma once\n\n"
        f"#define MEL_N_MELS    {n_mels}\n"
        f"#define MEL_N_FFT     {N_FFT}\n"
        f"#define MEL_FFT_BINS  {n_bins}\n"
        f"#define MEL_N_FRAMES  {N_FRAMES}\n"
        f"#define MEL_HOP       {HOP_LENGTH}\n"
        f"#define MEL_N_SAMPLES {N_SAMPLES}\n"
        f"#define NORM_MEAN     {mean:.8f}f\n"
        f"#define NORM_STD      {std:.8f}f\n\n"
        f"const float mel_filterbank[{n_mels}][{n_bins}] = {{\n"
        + ",\n".join(rows)
        + "\n};\n"
    )


def main():
    norm = json.loads((MODEL_DIR / "ast_norm_stats.json").read_text())
    mean, std = norm["mean"], norm["std"]

    model_path = MODEL_DIR / "ast_model_best.h5"
    if not model_path.exists():
        model_path = MODEL_DIR / "ast_model.h5"
    if not model_path.exists():
        raise FileNotFoundError("No AST model found — run train_ast.py first")
    print(f"Loading {model_path.name}")

    model = tf.keras.models.load_model(
        str(model_path),
        custom_objects={
            "AddPositionalEmbedding":    AddPositionalEmbedding,
            "StaticMultiHeadAttention":  StaticMultiHeadAttention,
        },
    )
    model.summary()

    # Wrap with a static batch=1 input so TFLite constant-folds all dynamic
    # shape ops (SHAPE, PACK, REDUCE_PROD) that 4-D BatchMatMul generates.
    static_inp = tf.keras.Input(batch_shape=(1, N_FRAMES, N_MELS, 1))
    static_model = tf.keras.Model(static_inp, model(static_inp, training=False))

    converter = tf.lite.TFLiteConverter.from_keras_model(static_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset(mean, std)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8
    converter._experimental_disable_per_channel_quantization_for_dense_layers = True

    print("Converting to TFLite INT8...")
    tflite_bytes = converter.convert()
    (MODEL_DIR / "ast_model.tflite").write_bytes(tflite_bytes)
    print(f"ast_model.tflite: {len(tflite_bytes) / 1024:.1f} KB")

    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    (INCLUDE_DIR / "model_data.h").write_text(bytes_to_c_array(tflite_bytes))
    (INCLUDE_DIR / "mel_filterbank.h").write_text(mel_filterbank_header(mean, std))
    print("Wrote firmware/include/model_data.h")
    print("Wrote firmware/include/mel_filterbank.h")
    print("\nNext: cd firmware && pio run -e wifi_inference --target upload")


if __name__ == "__main__":
    main()
