"""Convert trained CNN to TFLite INT8 + generate C headers for firmware."""

from __future__ import annotations

import json
from pathlib import Path

import librosa
import numpy as np
import tensorflow as tf

SAMPLE_RATE = 16000
N_FFT = 512
HOP_LENGTH = 160
N_MELS = 64
DURATION = 1.0
N_FRAMES = (int(SAMPLE_RATE * DURATION) - N_FFT) // HOP_LENGTH + 1  # 97

CLASSES = ["fall", "cough", "normal", "other"]
TRAIN_DIR = Path("data/train")
MODEL_DIR = Path("models")
INCLUDE_DIR = Path("firmware/include")


def load_mel(wav_path: Path, mean: float, std: float) -> np.ndarray | None:
    try:
        y, _ = librosa.load(wav_path, sr=SAMPLE_RATE, mono=True, duration=DURATION)
        target = int(SAMPLE_RATE * DURATION)
        if len(y) < target:
            y = np.pad(y, (0, target - len(y)))
        y = y[:target]
        mel = librosa.feature.melspectrogram(
            y=y, sr=SAMPLE_RATE, n_fft=N_FFT, hop_length=HOP_LENGTH,
            n_mels=N_MELS, fmin=20, fmax=8000, center=False,
        )
        log_mel = librosa.power_to_db(mel, ref=np.max).astype(np.float32).T
        if log_mel.shape[0] > N_FRAMES:
            log_mel = log_mel[:N_FRAMES]
        elif log_mel.shape[0] < N_FRAMES:
            log_mel = np.pad(log_mel, ((0, N_FRAMES - log_mel.shape[0]), (0, 0)))
        return ((log_mel - mean) / std)[np.newaxis, ..., np.newaxis].astype(np.float32)
    except Exception:
        return None


def representative_dataset(mean: float, std: float):
    def gen():
        count = 0
        for class_dir in sorted(TRAIN_DIR.iterdir()):
            if not class_dir.is_dir():
                continue
            for wav_path in list(class_dir.rglob("*.wav"))[:40]:
                mel = load_mel(wav_path, mean, std)
                if mel is not None:
                    yield [mel]
                    count += 1
                    if count >= 200:
                        return
    return gen


def bytes_to_c_array(data: bytes, var_name: str = "model_data") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk))
    return (
        "// Auto-generated by convert_tflite.py — do not edit\n"
        "#pragma once\n\n"
        f"alignas(8) const unsigned char {var_name}[] = {{\n"
        + ",\n".join(lines)
        + "\n};\n"
        f"const unsigned int {var_name}_len = {len(data)};\n"
    )


def mel_filterbank_header(mean: float, std: float) -> str:
    fb = librosa.filters.mel(
        sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=N_MELS, fmin=20, fmax=8000
    ).astype(np.float32)
    n_mels, n_bins = fb.shape

    rows = []
    for row in fb:
        rows.append("  {" + ", ".join(f"{v:.8f}f" for v in row) + "}")

    return (
        "// Auto-generated by convert_tflite.py — do not edit\n"
        "#pragma once\n\n"
        f"#define MEL_N_MELS    {n_mels}\n"
        f"#define MEL_N_FFT     {N_FFT}\n"
        f"#define MEL_FFT_BINS  {n_bins}\n"
        f"#define MEL_N_FRAMES  {N_FRAMES}\n"
        f"#define MEL_HOP       {HOP_LENGTH}\n"
        f"#define NORM_MEAN     {mean:.8f}f\n"
        f"#define NORM_STD      {std:.8f}f\n\n"
        f"const float mel_filterbank[{n_mels}][{n_bins}] = {{\n"
        + ",\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    # Prefer best checkpoint if available
    model_path = MODEL_DIR / "cnn_model_best.h5"
    if not model_path.exists():
        model_path = MODEL_DIR / "cnn_model.h5"
    if not model_path.exists():
        raise FileNotFoundError(f"No model found in {MODEL_DIR} — run train_cnn.py first")
    print(f"Loading model: {model_path}")

    norm = json.loads((MODEL_DIR / "cnn_norm_stats.json").read_text())
    mean, std = norm["mean"], norm["std"]

    model = tf.keras.models.load_model(str(model_path))

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    # Pure float32 — no quantization, maximum library compatibility

    print("Converting to TFLite (pure float32)...")
    tflite_bytes = converter.convert()

    (MODEL_DIR / "model.tflite").write_bytes(tflite_bytes)
    print(f"model.tflite: {len(tflite_bytes) / 1024:.1f} KB")

    INCLUDE_DIR.mkdir(parents=True, exist_ok=True)

    (INCLUDE_DIR / "model_data.h").write_text(bytes_to_c_array(tflite_bytes))
    print(f"Wrote firmware/include/model_data.h")

    (INCLUDE_DIR / "mel_filterbank.h").write_text(mel_filterbank_header(mean, std))
    print(f"Wrote firmware/include/mel_filterbank.h")

    print("\nNext steps:")
    print("  cd firmware && pio run -e wifi_inference --target upload")


if __name__ == "__main__":
    main()
